### ISSUE TITLE
Why bitshares/bitshares-2 is not an automated build?

### ISSUE THREAD

**Issue by noisy** [xeroc/bitshares-docker#2]
I think it would be good to have an dockerfile listed in https://hub.docker.com/r/bitshares/bitshares-2/, as it is with other bitshares images.

**Comment by xeroc** [comment]
Simply because the build process gets killed. The machines at docker hub are limited to 1 or 2 GB of RAM. That is not enough to build bitshares-2. The other containers build on top of this container and don't need that much RAM.

It's not a perfect solution yet since people are required to trust me that I have not tampered with the bitshares-2 container, I know. I am still trying to figure out how to get the funds for a payed plan.
